### PR TITLE
Support fragments in bundling

### PR DESCRIPTION
**Pull request by ahie**
Additionally fixes bundling of CSS and JavaScript.

The jars in test resources have been replaced with locally built 
snapshots due to the package renaming recently done in flow.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-maven-plugin/36)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[README.md, line 156 at r1](https://reviewable.io:443/reviews/vaadin/flow-maven-plugin/36#-L0eF2rTKuTsPB53WGbN:-L0eF2rTKuTsPB53WGbO:blos1l0) ([raw file](https://github.com/vaadin/flow-maven-plugin/blob/533a8cc36ab0df66b213b99738bb35e6f2339fb0/README.md#L156)):*
> ```Markdown
>   'fragments': [
>     [
>       'frontend/bower_components/vaadin-icons/vaadin-icons.html'
> ```

The `frontend/` path confuses me a bit, is this `transpileEs6SourceDirectory` directory name? 
Then it can be changed and the user will be a bit surprised when he realises that he needs to change those paths everywhere in the file.

Should we instead sate in the documentation that the user specifies fragments with the source directory relative paths?
Very connected with `workingDirectory` usage later, see comments below.

---

*[src/main/java/com/vaadin/flow/plugin/common/FrontendToolsManager.java, line 164 at r1](https://reviewable.io:443/reviews/vaadin/flow-maven-plugin/36#-L0eE4IeXxIYMVgL2a2z:-L0eE4IeXxIYMVgL2a3-:b1c88dk) ([raw file](https://github.com/vaadin/flow-maven-plugin/blob/533a8cc36ab0df66b213b99738bb35e6f2339fb0/src/main/java/com/vaadin/flow/plugin/common/FrontendToolsManager.java#L164)):*
> ```Java
>             BundleConfigurationReader bundleConfigurationReader = new BundleConfigurationReader(bundleConfigurationFile);
>             fragments = bundleConfigurationReader.getFragments();
>             fragments.stream().flatMap(Set::stream).forEach(this::checkFragmentFile);
> ```

We do the same operation in `createShellFile` and something very similar in `createFragmentFiles`.
Can we instead put all this logic to `BundleConfigurationReader` and make him return a `Map<String, Set<String>>` instead of `Set<Set<String>>?

Map will return fragment file name and fragments contained.

I see the following benefits:
1. We iterate less: `createShellFile` will simply call `Map::values` (`createFragmentFiles` will iterate over the map anyway, which is more or less the same)
2. We validate paths instantly in during the map construction
3. We hide more logic in `BundleConfigurationReader` so we can test it
4. Code is a bit easier to read

What do you think?

---

*[src/main/java/com/vaadin/flow/plugin/common/FrontendToolsManager.java, line 247 at r1](https://reviewable.io:443/reviews/vaadin/flow-maven-plugin/36#-L0eJnQqBYnOXclhJKf0:-L0eJAj9T22uwWaeo4MH:b-mcwiy3) ([raw file](https://github.com/vaadin/flow-maven-plugin/blob/533a8cc36ab0df66b213b99738bb35e6f2339fb0/src/main/java/com/vaadin/flow/plugin/common/FrontendToolsManager.java#L247)):*
> workingDirectory

I guess you can use class field here, but up to you.
I have had a brain fart with this one, so if you remove the same param from `createShellFile` method, it would be super awesome.

---

*[src/main/java/com/vaadin/flow/plugin/common/FrontendToolsManager.java, line 277 at r1](https://reviewable.io:443/reviews/vaadin/flow-maven-plugin/36#-L0eIBHuBNtm1CnpNAHW:-L0eIBHuBNtm1CnpNAHX:blmpdly) ([raw file](https://github.com/vaadin/flow-maven-plugin/blob/533a8cc36ab0df66b213b99738bb35e6f2339fb0/src/main/java/com/vaadin/flow/plugin/common/FrontendToolsManager.java#L277)):*
> ```Java
> 
>     private void checkFragmentFile(String fragmentFilePath) {
>         File fragmentFile = new File(workingDirectory, fragmentFilePath);
> ```

Are you sure that `new File(workingDirectory, fragmentFilePath)` is a correct path to check?

I presume that this works only because now `transpileEs6SourceDirectory` default is `${project.build.directory}/frontend/` and `workingDirectory` default is `${project.build.directory}/`

It is not true in general case, so I presume that you need to use `transpileEs6SourceDirectory` which is passed as `es6SourceDirectory` in the class method.

---

*[src/main/resources/gulpfile.js, line 35 at r1](https://reviewable.io:443/reviews/vaadin/flow-maven-plugin/36#-L0eKJARHgYsmiJDmWkO:-L0eKJARHgYsmiJDmWkP:b-3xt9q2) ([raw file](https://github.com/vaadin/flow-maven-plugin/blob/533a8cc36ab0df66b213b99738bb35e6f2339fb0/src/main/resources/gulpfile.js#L35)):*
> ```JavaScript
> function build() {
>     const workingDirectory = __dirname;
>     const polymerProperties = {
> ```

Should not be done in this PR, just asking for opinion: how do you think, would it make any sense to stop writing stuff into the file and create a json file already?

---

*[src/main/resources/package.json, line 19 at r1](https://reviewable.io:443/reviews/vaadin/flow-maven-plugin/36#-L0eL2ZRi6sfkSxILQZQ:-L0eL2ZRi6sfkSxILQZR:bftytgh) ([raw file](https://github.com/vaadin/flow-maven-plugin/blob/533a8cc36ab0df66b213b99738bb35e6f2339fb0/src/main/resources/package.json#L19)):*
> ```JSON
>     "polymer-build": "2.1.1",
>     "merge-stream": "1.0.1",
>     "vinyl": "1.2.0",
> ```

Should we update the lock either?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-maven-plugin/36)*

**Comment by ahie** [comment]
Review status: 15 of 16 files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 156 at r1](https://reviewable.io:443/reviews/vaadin/flow-maven-plugin/36#-L0eF2rTKuTsPB53WGbN:-L0i0u0O0iWM7THddvuh:b4h30b7) ([raw file](https://github.com/vaadin/flow-maven-plugin/blob/533a8cc36ab0df66b213b99738bb35e6f2339fb0/README.md#L156)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

The `frontend/` path confuses me a bit, is this `transpileEs6SourceDirectory` directory name? 
Then it can be changed and the user will be a bit surprised when he realises that he needs to change those paths everywhere in the file.

Should we instead sate in the documentation that the user specifies fragments with the source directory relative paths?
Very connected with `workingDirectory` usage later, see comments below.
</blockquote></details>

If I'm not mistaken, `transpileEs6SourceDirectory` should always match `copyOutputDirectory` of the copy step. That way we could document that the fragments need to be relative to the `frontendWorkingDirectory` and fix the logic accordingly?

---

*[src/main/resources/gulpfile.js, line 35 at r1](https://reviewable.io:443/reviews/vaadin/flow-maven-plugin/36#-L0eKJARHgYsmiJDmWkO:-L0huzKzFACD32cw3Jno:b-f9c1ce) ([raw file](https://github.com/vaadin/flow-maven-plugin/blob/533a8cc36ab0df66b213b99738bb35e6f2339fb0/src/main/resources/gulpfile.js#L35)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Should not be done in this PR, just asking for opinion: how do you think, would it make any sense to stop writing stuff into the file and create a json file already?
</blockquote></details>

Actually I kind of prefer the way it is done now. Its simple and very easy to understand where the values come from. If there's some case in the future where this doesn't work/becomes really ugly it should be changed, but for now I think this approach is fine.

---

*[src/main/resources/package.json, line 19 at r1](https://reviewable.io:443/reviews/vaadin/flow-maven-plugin/36#-L0eL2ZRi6sfkSxILQZQ:-L0huyMA8kc67luRhh7s:b-896fix) ([raw file](https://github.com/vaadin/flow-maven-plugin/blob/533a8cc36ab0df66b213b99738bb35e6f2339fb0/src/main/resources/package.json#L19)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Should we update the lock either?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-maven-plugin/36)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line 156 at r1](https://reviewable.io:443/reviews/vaadin/flow-maven-plugin/36#-L0eF2rTKuTsPB53WGbN:-L0i28QlAFcrSw9AZnCU:b-f208j) ([raw file](https://github.com/vaadin/flow-maven-plugin/blob/533a8cc36ab0df66b213b99738bb35e6f2339fb0/README.md#L156)):*
> transpileEs6SourceDirectory should always match copyOutputDirectory of the copy step. 

Not really required but intended to be so, yeah.

> That way we could document that the fragments need to be relative to the frontendWorkingDirectory and fix the logic accordingly?


Exactly what I meant, yeah.

---

*[src/main/resources/gulpfile.js, line 35 at r1](https://reviewable.io:443/reviews/vaadin/flow-maven-plugin/36#-L0eKJARHgYsmiJDmWkO:-L0i1rrGjlv0b0usx_ci:b-83sjo4) ([raw file](https://github.com/vaadin/flow-maven-plugin/blob/533a8cc36ab0df66b213b99738bb35e6f2339fb0/src/main/resources/gulpfile.js#L35)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Actually I kind of prefer the way it is done now. Its simple and very easy to understand where the values come from. If there's some case in the future where this doesn't work/becomes really ugly it should be changed, but for now I think this approach is fine.
</blockquote></details>

Nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-maven-plugin/36)*

**Comment by ahie** [comment]
Review status: 14 of 16 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/plugin/common/FrontendToolsManager.java, line 164 at r1](https://reviewable.io:443/reviews/vaadin/flow-maven-plugin/36#-L0eE4IeXxIYMVgL2a2z:-L0n992H0ZiVuhvgFUGS:bvbl3or) ([raw file](https://github.com/vaadin/flow-maven-plugin/blob/533a8cc36ab0df66b213b99738bb35e6f2339fb0/src/main/java/com/vaadin/flow/plugin/common/FrontendToolsManager.java#L164)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

We do the same operation in `createShellFile` and something very similar in `createFragmentFiles`.
Can we instead put all this logic to `BundleConfigurationReader` and make him return a `Map<String, Set<String>>` instead of `Set<Set<String>>?

Map will return fragment file name and fragments contained.

I see the following benefits:
1. We iterate less: `createShellFile` will simply call `Map::values` (`createFragmentFiles` will iterate over the map anyway, which is more or less the same)
2. We validate paths instantly in during the map construction
3. We hide more logic in `BundleConfigurationReader` so we can test it
4. Code is a bit easier to read

What do you think?
</blockquote></details>

Not really sure that logic belongs to the bundle configuration reader. A couple reasons are that the fragments are not named in the configuration file and creating the main bundle depends on knowledge of what the fragments include. Though to simplify the code a new helper class could be introduced to handle the writing of the files based on some inputs that could be better tested.

---

*[src/main/java/com/vaadin/flow/plugin/common/FrontendToolsManager.java, line 247 at r1](https://reviewable.io:443/reviews/vaadin/flow-maven-plugin/36#-L0eJnQqBYnOXclhJKf0:-L0ilWrWb-DsXGECX4vT:b-896fix) ([raw file](https://github.com/vaadin/flow-maven-plugin/blob/533a8cc36ab0df66b213b99738bb35e6f2339fb0/src/main/java/com/vaadin/flow/plugin/common/FrontendToolsManager.java#L247)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> workingDirectory

I guess you can use class field here, but up to you.
I have had a brain fart with this one, so if you remove the same param from `createShellFile` method, it would be super awesome.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-maven-plugin/36)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-maven-plugin/36)*

**Pull request merged**
